#!/usr/bin/env node
// Pivot onboarding. Zero dependencies: node's stdlib plus the Supabase CLI.
//
// Pressing enter through every question gives a working local stack. Re-running
// is safe — migrations, buckets, secrets and the cron job are all idempotent.

import { createInterface } from 'node:readline/promises'
import { spawnSync } from 'node:child_process'
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { randomUUID } from 'node:crypto'
import { stdin, stdout } from 'node:process'

const rl = createInterface({ input: stdin, output: stdout })
const C = { dim: '\x1b[2m', b: '\x1b[1m', g: '\x1b[32m', y: '\x1b[33m', r: '\x1b[31m', x: '\x1b[0m' }
const say = (s = '') => console.log(s)
const step = (s) => say(`\n${C.b}${s}${C.x}`)
const ok = (s) => say(`  ${C.g}✓${C.x} ${s}`)
const warn = (s) => say(`  ${C.y}!${C.x} ${s}`)

async function ask(q, dflt = '') {
  const hint = dflt ? ` ${C.dim}[${dflt}]${C.x}` : ''
  const a = (await rl.question(`  ${q}${hint} `)).trim()
  return a || dflt
}
const askYes = async (q, dflt = true) =>
  /^y/i.test(await ask(`${q} ${C.dim}(y/n)${C.x}`, dflt ? 'y' : 'n'))

async function askSecret(q, existing) {
  if (existing) {
    const keep = await ask(`${q} ${C.dim}(enter to keep the existing one)${C.x}`, '·')
    if (keep === '·') return existing
    return keep
  }
  let v = ''
  while (!v) {
    v = await ask(q)
    if (!v) warn('That one is required.')
  }
  return v
}

/** Runs a command, streaming output; throws with context rather than a bare code. */
function run(cmd, args, { capture = false, allowFail = false } = {}) {
  const r = spawnSync(cmd, args, { encoding: 'utf8', stdio: capture ? 'pipe' : 'inherit' })
  if (r.error) throw new Error(`Could not run \`${cmd}\`: ${r.error.message}`)
  if (r.status !== 0 && !allowFail) {
    const detail = capture ? `\n${(r.stderr || r.stdout || '').trim()}` : ''
    throw new Error(`\`${cmd} ${args.join(' ')}\` exited with ${r.status}.${detail}`)
  }
  return { code: r.status, out: (r.stdout ?? '').trim(), err: (r.stderr ?? '').trim() }
}

const sql = (query, target) => run('supabase', ['db', 'query', target, query], { capture: true })

/** Existing answers, so re-running the wizard is an edit rather than a retype. */
function readEnv(path) {
  if (!existsSync(path)) return {}
  return Object.fromEntries(
    readFileSync(path, 'utf8').split('\n')
      .map((l) => l.match(/^([A-Z0-9_]+)=(.*)$/))
      .filter(Boolean)
      .map((m) => [m[1], m[2].replace(/^"|"$/g, '')]),
  )
}

const writeEnv = (path, vars, note) =>
  writeFileSync(path, `# ${note}\n# Generated by pnpm setup — edit freely, re-running merges your answers.\n\n` +
    Object.entries(vars).map(([k, v]) => `${k}=${v}`).join('\n') + '\n')

// ── 1. Where does this run ───────────────────────────────────────────────────
async function chooseTarget(prev) {
  step('1/6  Supabase project')
  const local = await askYes('Use a local Supabase stack (docker)?', prev.SUPABASE_URL ? prev.SUPABASE_URL.includes('127.0.0.1') : true)
  if (local) return { target: '--local', local: true, functionsUrl: 'http://host.docker.internal:54321/functions/v1', deploy: false }

  const ref = await ask('Project ref (the subdomain of your project URL)', prev.SUPABASE_PROJECT_REF)
  if (!ref) throw new Error('A project ref is required for a hosted project.')
  return {
    target: '--linked',
    ref,
    url: await ask('API URL', prev.SUPABASE_URL || `https://${ref}.supabase.co`),
    anonKey: await askSecret('Anon key', prev.SUPABASE_ANON_KEY),
    serviceKey: await askSecret('Service role key', prev.SUPABASE_SERVICE_ROLE_KEY),
    functionsUrl: `https://${ref}.supabase.co/functions/v1`,
    deploy: true,
  }
}

/** Brings the stack up (local) or links it (hosted), and fills in the keys. */
/**
 * The local stack is containers. When the engine is down `supabase start`
 * fails deep inside a container inspect and reports an HTTP API version
 * instead of the cause, so check first and say the real thing.
 *
 * The signal is an empty server version, not the exit code: `docker info` can
 * exit 0 while the engine is unreachable.
 */
function requireDocker() {
  let version = ''
  try {
    version = run('docker', ['version', '--format', '{{.Server.Version}}'],
      { capture: true, allowFail: true }).out
  } catch {
    throw new Error(
      'Docker is not installed, and the local stack needs it.\n' +
      '  Install Docker Desktop (https://docs.docker.com/desktop), or re-run and\n' +
      '  choose a hosted Supabase project instead.',
    )
  }
  if (!version) {
    throw new Error(
      'Docker is installed but its engine is not responding — the daemon is not\n' +
      '  running, or is still starting up.\n\n' +
      '  Start Docker Desktop, wait until its whale icon stops animating, then\n' +
      '  re-run `pnpm setup`. `docker ps` succeeding is the signal it is ready.\n' +
      '  A hosted Supabase project needs no Docker at all.',
    )
  }
  return version
}

function connect(t) {
  if (!t.local) {
    run('supabase', ['link', '--project-ref', t.ref])
    ok(`linked to ${t.ref}`)
    return t
  }
  ok(`docker engine ${requireDocker()}`)
  let status = run('supabase', ['status', '-o', 'json'], { capture: true, allowFail: true })
  if (status.code !== 0) {
    say(`  ${C.dim}Starting the local stack (first run pulls images, this takes a while)…${C.x}`)
    run('supabase', ['start'])
    status = run('supabase', ['status', '-o', 'json'], { capture: true })
  }
  let s
  try {
    s = JSON.parse(status.out)
  } catch {
    throw new Error(`Could not read \`supabase status\`:\n${status.out || status.err}`)
  }
  ok('local stack is up')
  return { ...t, url: s.API_URL, anonKey: s.ANON_KEY, serviceKey: s.SERVICE_ROLE_KEY }
}

// ── 2. Auth ──────────────────────────────────────────────────────────────────
async function chooseAuth(prev) {
  step('2/6  Authentication')
  say(`  ${C.dim}On: Supabase Auth, each user sees only their own notes.`)
  say(`  Off: single local user, no sign-in screen — for a private instance.${C.x}`)
  const enabled = await askYes('Enable authentication?', prev.AUTH_ENABLED !== 'false')
  const localUserId = enabled ? '' : (prev.LOCAL_USER_ID || randomUUID())
  ok(enabled ? 'auth on' : `auth off — local user ${localUserId}`)
  return { enabled, localUserId }
}

// ── 3. Models ────────────────────────────────────────────────────────────────
async function chooseModels(prev) {
  step('3/6  OCR model')
  say(`  ${C.dim}Any OpenAI-compatible chat endpoint that accepts images.${C.x}`)
  const ocr = {
    baseUrl: await ask('Base URL', prev.OCR_BASE_URL || 'https://generativelanguage.googleapis.com/v1beta/openai/'),
    model: await ask('Model', prev.OCR_MODEL || 'gemini-flash-latest'),
    apiKey: await askSecret('API key', prev.OCR_API_KEY),
  }

  step('4/6  Embedding model')
  const embed = {
    baseUrl: await ask('Base URL', prev.EMBED_BASE_URL || 'https://api.openai.com/v1'),
    model: await ask('Model', prev.EMBED_MODEL || 'text-embedding-3-small'),
    dim: Number(await ask('Dimensions', prev.EMBED_DIM || '1536')),
  }
  if (!Number.isInteger(embed.dim) || embed.dim < 8 || embed.dim > 4096) {
    throw new Error(`Embedding dimension ${embed.dim} is not a plausible vector size.`)
  }
  embed.apiKey = ocr.baseUrl === embed.baseUrl
    ? await ask('API key (enter to reuse the OCR key)', prev.EMBED_API_KEY || ocr.apiKey)
    : await askSecret('API key', prev.EMBED_API_KEY)

  return { ocr, embed }
}

/**
 * The vector dimension is baked into the schema, so choosing one is a migration
 * edit — and it must happen before anything applies those migrations.
 */
function rewriteDimension(dim) {
  let changed = false
  for (const f of ['supabase/migrations/0001_init.sql', 'supabase/migrations/0002_rpc.sql']) {
    const before = readFileSync(f, 'utf8')
    const after = before.replace(/vector\(\d+\)/g, `vector(${dim})`)
    if (after !== before) { writeFileSync(f, after); changed = true }
  }
  if (changed) ok(`schema set to ${dim} dimensions`)
}

/** Refuse to reinterpret vectors that are already stored at another width. */
function assertDimension(dim, target) {
  const live = sql(
    `select coalesce(atttypmod, -1) as d from pg_attribute
       where attrelid = to_regclass('public.notes') and attname = 'embedding'`,
    target,
  ).out
  const m = live.match(/\b(\d{2,4})\b/)
  if (m && Number(m[1]) !== dim) {
    throw new Error(
      `This database already stores ${m[1]}-dimension embeddings but you chose ${dim}.\n` +
      `Existing vectors cannot be reinterpreted. Either keep ${m[1]} dimensions, or reset the\n` +
      `database (supabase db reset) and re-run setup, which discards existing notes.`,
    )
  }
}

// ── 4. Provision ─────────────────────────────────────────────────────────────
function bootstrap({ target, functionsUrl, serviceKey }, auth) {
  // Parameterised over a CLI connection rather than a generated migration, so
  // the service key is never written into a file in the repo.
  const stmts = [
    `create extension if not exists supabase_vault with schema vault;`,
    // A row, not a database setting: `alter database ... set` on a custom
    // parameter needs superuser, which `postgres` is not on Supabase.
    auth.enabled
      ? `delete from public.app_config where key = 'local_user_id';`
      : `insert into public.app_config (key, value) values ('local_user_id', '${auth.localUserId}')
           on conflict (key) do update set value = excluded.value;`,
    // Vault is written through its functions, never its table: `postgres` has
    // SELECT and DELETE on vault.secrets and nothing else.
    `do $do$
       declare sid uuid;
       begin
         select id into sid from vault.secrets where name = 'pivot_service_key';
         if sid is null then
           perform vault.create_secret('${serviceKey}', 'pivot_service_key', 'Pivot worker auth');
         else
           perform vault.update_secret(sid, '${serviceKey}');
         end if;
       end
     $do$;`,
    `select cron.unschedule('pivot-process')
       where exists (select 1 from cron.job where jobname = 'pivot-process');`,
    `select cron.schedule('pivot-process', '10 seconds', $job$
       select net.http_post(
         url := '${functionsUrl}/process',
         headers := jsonb_build_object(
           'content-type', 'application/json',
           'authorization', 'Bearer ' || (select decrypted_secret from vault.decrypted_secrets where name = 'pivot_service_key')
         ),
         body := '{}'::jsonb,
         timeout_milliseconds := 60000
       );
     $job$);`,
  ]
  for (const s of stmts) {
    const r = sql(s, target)
    if (r.code !== 0) throw new Error(`Bootstrap statement failed:\n${s}\n${r.err || r.out}`)
  }
}

// ── Main ─────────────────────────────────────────────────────────────────────
async function main() {
  say(`${C.b}\n  Pivot setup${C.x}\n  ${C.dim}Enter accepts every default.${C.x}`)
  if (run('supabase', ['--version'], { capture: true, allowFail: true }).code !== 0) {
    throw new Error('The Supabase CLI is required: https://supabase.com/docs/guides/cli')
  }

  const prev = { ...readEnv('.env'), ...readEnv('.env.local') }
  const chosen = await chooseTarget(prev)
  const auth = await chooseAuth(prev)
  const { ocr, embed } = await chooseModels(prev)

  step('5/6  Provisioning')
  rewriteDimension(embed.dim)                 // before anything applies migrations
  const t = connect(chosen)
  assertDimension(embed.dim, t.target)
  run('supabase', ['db', 'push', t.target])   // additive; never drops existing notes
  ok('schema applied')

  const secrets = {
    AUTH_ENABLED: String(auth.enabled),
    LOCAL_USER_ID: auth.localUserId,
    OCR_BASE_URL: ocr.baseUrl, OCR_MODEL: ocr.model, OCR_API_KEY: ocr.apiKey,
    EMBED_BASE_URL: embed.baseUrl, EMBED_MODEL: embed.model, EMBED_API_KEY: embed.apiKey,
    EMBED_DIM: String(embed.dim),
  }

  if (t.deploy) {
    run('supabase', ['functions', 'deploy', 'ingest', '--project-ref', t.ref])
    run('supabase', ['functions', 'deploy', 'process', '--project-ref', t.ref])
    run('supabase', ['secrets', 'set', '--project-ref', t.ref,
      ...Object.entries(secrets).filter(([, v]) => v).map(([k, v]) => `${k}=${v}`)])
    ok('edge functions deployed and configured')
  } else {
    // Read by `supabase functions serve`, which `pnpm dev` runs. `supabase
    // start` has no way to pass env to a function, so serving them is not
    // optional locally — see scripts/dev.mjs.
    writeEnv('supabase/functions/.env', secrets, 'Local edge function environment')
    ok('local edge function environment written')
  }

  bootstrap(t, auth)
  ok('worker scheduled every 10s')

  step('6/6  Writing configuration')
  writeEnv('.env', { SUPABASE_URL: t.url, SUPABASE_ANON_KEY: t.anonKey, SUPABASE_SERVICE_ROLE_KEY: t.serviceKey, SUPABASE_PROJECT_REF: t.ref ?? '', SUPABASE_FUNCTIONS_URL: t.functionsUrl, ...secrets }, 'Server-side configuration. Never commit.')
  writeEnv('.env.local', {
    VITE_SUPABASE_URL: t.url,
    VITE_SUPABASE_ANON_KEY: t.anonKey,
    VITE_AUTH_ENABLED: String(auth.enabled),
  }, 'Frontend configuration. Only ever public values.')
  ok('.env and .env.local written')

  say(`\n${C.g}  Ready.${C.x}`)
  say(`  ${C.b}pnpm dev${C.x}        start the app${t.deploy ? '' : ' and serve the edge functions'}`)
  if (!t.deploy) {
    say(`  ${C.dim}                 the functions only have their keys while this runs${C.x}`)
    say(`  ${C.b}pnpm worker${C.x}     run the worker from your machine`)
    say(`  ${C.dim}                 (only if pg_cron cannot reach the edge runtime in docker)${C.x}`)
  }
  say(`  ${C.b}pnpm test${C.x}       run the pipeline's unit tests\n`)
}

main()
  .then(() => rl.close())
  .catch((e) => {
    say(`\n${C.r}  Setup failed.${C.x} ${e.message}\n`)
    rl.close()
    process.exit(1)
  })
